/**
 * Demo x402 Provider - Vercel Serverless Function
 * 
 * This endpoint simulates an x402-enabled provider that accepts payment
 * and returns a result. In production, this would be protected by x402 middleware.
 * 
 * For demo purposes, we skip actual payment verification and show the flow.
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Payment-Response');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // GET - Return x402 payment requirements (simulates 402 response)
  if (req.method === 'GET') {
    return res.status(200).json({
      x402: true,
      provider: 'IntentCast Demo Provider',
      description: 'Demo endpoint that simulates x402 payment flow',
      pricing: {
        price: '$0.01',
        network: 'eip155:84532',
        scheme: 'exact',
        payTo: process.env.DEMO_PROVIDER_WALLET || '0x536100EFF5aE2F494A961C7F874e90b3B5Ac1eC4',
      },
      endpoints: {
        fulfill: 'POST /api/demo-fulfill',
      },
    });
  }

  // POST - Fulfill request (in production, x402 middleware verifies payment first)
  if (req.method === 'POST') {
    const { intentId, input } = req.body || {};

    // Simulate processing
    const preview = typeof input === 'string' ? input.substring(0, 100) : JSON.stringify(input).substring(0, 100);
    
    // Simulate work (e.g., summarization)
    const result = {
      success: true,
      intentId: intentId || 'demo-intent',
      provider: 'IntentCast Demo Provider',
      result: `Processed: "${preview}..."`,
      summary: 'This is a demo summary generated by the IntentCast demo provider. In production, this would be real AI-generated content.',
      timestamp: new Date().toISOString(),
      payment: {
        status: 'demo',
        note: 'In production, payment would be verified via x402 before this response',
        amount: '$0.01',
        network: 'Base Sepolia',
      },
    };

    return res.status(200).json(result);
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
